### ISSUE TITLE
Is there any screenshots or demonstration?

### ISSUE THREAD

**Issue by dinhkhanh** [thinkoverit/Magento-Gallery-Extension#2]

**Comment by thinkoverit** [comment]
Hello,

You can find them here http://www.magentocommerce.com/magento-connect/toit-gallery-1.html
Extension is in alpha stage yet, But fully functional.
If you find any issues please share I will try my best to respond.

**Comment by dinhkhanh** [comment]
Thank you for speedy response.
But your link is automatically redirected to http://www.magentocommerce.com/magento-connect/

**Comment by thinkoverit** [comment]
My Bad, Please have alook at http://shop.thinkoverit.com/gallery/index/view/,
Site speed is too slow so please bear with me.

**Comment by dinhkhanh** [comment]
Thank you for this.
